// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @dr.pogodin/react-native-fs
#include <winrt/ReactNativeFs.h>

// Includes from react-native-linear-gradient
#include <winrt/BVLinearGradient.h>

// Includes from react-native-permissions
#include <winrt/RNPermissions.h>

// Includes from react-native-screens
#include <winrt/RNScreens.h>

// Includes from react-native-video
#include <winrt/ReactNativeVideoCPP.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @dr.pogodin/react-native-fs
    packageProviders.Append(winrt::ReactNativeFs::ReactPackageProvider());
    // IReactPackageProviders from react-native-linear-gradient
    packageProviders.Append(winrt::BVLinearGradient::ReactPackageProvider());
    // IReactPackageProviders from react-native-permissions
    packageProviders.Append(winrt::RNPermissions::ReactPackageProvider());
    // IReactPackageProviders from react-native-screens
    packageProviders.Append(winrt::RNScreens::ReactPackageProvider());
    // IReactPackageProviders from react-native-video
    packageProviders.Append(winrt::ReactNativeVideoCPP::ReactPackageProvider());
}

}
